---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 1m
  releaseName: istio-base
  targetNamespace: istio-system
  install:
    createNamespace: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-istiod
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 1m
  releaseName: istiod
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 1m
  releaseName: istio-ingress
  targetNamespace: istio-system
  dependsOn:
    - name: istio-istiod
       

