---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '55.5.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  releaseName: prometheus
  targetNamespace: prometheus
  install:
    createNamespace: true

